from dataclasses import dataclass, field
from google.cloud import storage
from collections import deque
from pathlib import Path
import re

BUCKET_NAME = "cloud-computing-homework-2"
GCS_DIRECTORY = "pages/"
LOCAL_DIR = "graph-files"

"""
Grab the contents of every html file in my bucket as a string
Outputs the dictionary with example html_pages[1001] = <HTML BLOB>
"""
def get_file_contents_from_GCS(bucket_name: str = BUCKET_NAME, directory: str = GCS_DIRECTORY) -> dict[int, str]:
    client = storage.Client()

    # Client.list_blobs returns an iterator of all my blobs in my bucket
    # A blob is just a reference to a file in GCS, not a file itself
    blob_iterator = client.list_blobs(bucket_name)

    # Consume my iterator into a list 
    blobs = list(blob_iterator)

    # Download the contents of every blob into local memory
    html_pages = {}
    for blob in blobs:
        # stem is the filename minus the filetype
        stem = Path(blob.name).stem
        html_pages[int(stem)] = blob.download_as_text()

    return html_pages

"""
Grab the contents of all the html files in my subdirectory and return that as a string
I am using this function for tests
Outputs the dictionary with example html_pages[1001] = <HTML BLOB>
"""
def get_file_contents_from_disk(directory: str = LOCAL_DIR) -> dict[int, str]:
    # Grab my current directory, jump up, then go into the directory of my html files
    graph_files_dir = Path(__file__).parent / directory


    html_pages = {}
    for path in graph_files_dir.glob("*.html"):
        html_pages[int(path.stem)] = path.read_text(encoding="utf-8")


    return html_pages



"""Return every href value in the page as a list of strings"""
def parse_links(html: str) -> list[int]:
    # This regex was generated by AI. I don't want to make this myself
    LINK_RE = re.compile(r'href\s*=\s*["\'](\d+)\.html["\']', re.IGNORECASE)
    return [int(n) for n in LINK_RE.findall(html)]



"""Builds my graph representation. Outer list is 0 - 9999. Inner list is all the outgoing edges """
def build_graph_representation(pages: dict[int, str]) -> list[list[int]]:
    # I need to presize my list
    adjacency_list = [[] for _ in range(len(pages))]
    for page_name, page_contents in pages.items():
        adjacency_list[page_name] = parse_links(page_contents)

    return adjacency_list


######################################################################################################

@dataclass
class GraphStats:
    outgoing_mean: float
    outgoing_median: int
    outgoing_minimum: int
    outgoing_maximum: int
    outgoing_quintiles: list[int]
    incoming_mean: float
    incoming_median: int
    incoming_minimum: int
    incoming_maximum: int
    incoming_quintiles: list[int]


"""Sum divided by count."""
def mean(values: list[int]) -> float:
    return sum(values) / len(values)

"""Gets the middle value"""
def median(values: list[int]) -> int:
    ordered = sorted(values)
    mid = len(ordered) // 2
    return ordered[mid]


"""The 20th, 40th, 60th and 80th percentile cut points"""
def quintiles(values: list[int]) -> list[int]:
    # sort my list
    ordered = sorted(values)
    list_length = len(ordered)

    cuts = []
    for i in range(1, 5):
        # 2000, 4000, 6000, 8000 
        cutoff_index = i * list_length // 5   
        # get the element at that index and add it to cuts     
        cuts.append(ordered[cutoff_index])

    return cuts


"""Compute the mean, median, min and max of incoming and outgoing links across all pages"""
def compute_link_properties(pages: list[list[int]]) -> GraphStats:
    degrees_out: list[int] = [len(page) for page in pages]

    # Creates a list of zeros, one per page: [0, 0, 0, ..., 0] with len(pages) entries.
    in_counts = [0] * len(pages)
    for targets in pages:
        # targets is one pages outgoing link list
        for target in targets:
            # For each page that the current page links to, 
            # bump the incoming links counter.
            in_counts[target] += 1

    return GraphStats(
        outgoing_mean=mean(degrees_out),
        outgoing_median=median(degrees_out),
        outgoing_minimum=min(degrees_out),
        outgoing_maximum=max(degrees_out),
        outgoing_quintiles=quintiles(degrees_out),
        incoming_mean=mean(in_counts),
        incoming_median=median(in_counts),
        incoming_minimum=min(in_counts),
        incoming_maximum=max(in_counts),
        incoming_quintiles=quintiles(in_counts),
    )


#############################################################

"""Return the PageRank score of every page, indexed the same way as `graph`."""
def compute_pagerank(graph: list[list[int]], iterations: int = 50) -> list[float]:
    n = len(graph)
    # Creates a list of size n where each item is (1 / n)
    scores = [1.0 / n] * n

    # loop 50 times so the scores get more accurate
    for _ in range(iterations):
        # Creates a list of size n where each item is 0.0
        # This is the output of this iteration of pagerank
        new_scores = [0.0] * n

        # go through one iteration of the graph
        # and update all the page ranks 
        for page, targets in enumerate(graph):
            # If the target list is empty skip the iteration
            # this prevents division by 0
            if not targets:
                continue                 

            # calculate the current page rank
            cur_pagerank = scores[page] / len(targets)
            # Sum up all neighboring pageranks
            for target in targets:
                new_scores[target] += cur_pagerank
        # Update the overall scores        
        scores = new_scores

    return scores

"""Return the top-k (page, score) pairs, highest score first."""
def top_pages(scores: list[float], k: int = 5) -> list[tuple[int, float]]:
    ranked = sorted(enumerate(scores), key=lambda pair: pair[1], reverse=True)
    return ranked[:k]



"""
Calculate pagerank using the original algorithm, not the simplified one above.

Stops once the total of all PageRank scores changes by less than
`change_threshold` (0.5%) between one iteration and the next.
"""
def compute_original_pagerank(
    graph: list[list[int]],
    damping: float = 0.85,
    change_threshold: float = 0.005,
    max_iterations: int = 1000,
) -> tuple[list[float], int]:
    n = len(graph)
    scores = [1.0 / n] * n
    previous_total = sum(scores)

    for iteration in range(1, max_iterations + 1):
        new_scores = [(1.0 - damping) / n] * n

        for page, targets in enumerate(graph):
            if not targets:
                continue 

            # Add in damping, which is a random factor meant to
            # prevent closed loops in the page rank algorithm
            share = damping * scores[page] / len(targets)
            for target in targets:
                new_scores[target] += share

        new_total = sum(new_scores)

        # calculate how much the score changed from the previous iteration 
        percent_change = abs(new_total - previous_total) / previous_total

        scores = new_scores
        previous_total = new_total

        # if the score changed from the previous iteration less than 
        # our change threshhold, we have reached a point where
        # we don't need to run our algo any more
        if percent_change < change_threshold:
            break

    return scores, iteration


#####################################################################################

"""
Distance from `source` to every node.
Unreachable nodes are left at -1.
"""
def bfs_distances(graph: list[list[int]], source: int) -> list[int]:
    n = len(graph)
    distance = [-1] * n
    distance[source] = 0
    queue = deque([source])

    while queue:
        # give me the leftmost element of my deque
        # this is the outer vertex
        current = queue.popleft()
        # for every elements neighbor
        for neighbor in graph[current]:
            # if that neighbor has not been visited before
            if distance[neighbor] == -1:
                # Set the distance source to 1 greater than the distance from current
                # current could have already been a neighbor because of the outer loop
                # so if you are two away from the source, you get 2 + 1.
                distance[neighbor] = distance[current] + 1
                queue.append(neighbor)

    return distance

"""
Give me the closeness centrality of a graph and a node
"""
def closeness_centrality(graph: list[list[int]], node: int) -> float:
    n = len(graph)
    # gives me a graph that has the data I need for CS
    # given as a list of number [-1, 2, 3, ... N]
    distances = bfs_distances(graph, node)

    # If node is disconnected from graph return 0
    # otherwise filter list
    reachable = [d for d in distances if d > 0]
    if not reachable:
        return 0.0

    reachable_count = len(reachable)
    total_distance = sum(reachable)

    # (reachable_count / total_distance) is the calculation on 
    # the slides for closeness centrality for a given node
    #
    # (reachable_count / (n - 1)) is what fraction of the entire graph 
    # this node can actually get to. Otherwise, one subgraph with a very close neighbor 
    # could beat out a bigger graph with 97 links
    return (reachable_count / (n - 1)) * (reachable_count / total_distance)


"""The page with the highest closeness centrality, and its score."""
def get_most_central_page(graph: list[list[int]]) -> tuple[int, float]:
    best_page, best_score = -1, -1.0
    for node in range(len(graph)):
        score = closeness_centrality(graph, node)
        if score > best_score:
            best_page, best_score = node, score
    return best_page, best_score





if __name__ == "__main__":
    output = get_file_contents_from_GCS()
    # output = get_file_contents_from_disk()
    graph_rep = build_graph_representation(output)
    statistics = compute_link_properties(graph_rep)
    print(statistics)
    page_rank = compute_pagerank(graph_rep)
    page_rank_original = compute_original_pagerank(graph_rep)
    print(f'The top 5 page ranks are {top_pages(page_rank)}')
    print(f'The top 5 page ranks from original algo are {top_pages(page_rank)}')
    most_central_page = get_most_central_page(graph_rep)
    print(f'The most central page is {most_central_page}')
    




