from google.cloud import storage
from pathlib import Path
import re

BUCKET_NAME = "cloud-computing-homework-2"
GCS_DIRECTORY = "pages/"
LOCAL_DIR = "graph-files"

"""
Grab the contents of every html file in my bucket as a string
Outputs the dictionary with example html_pages[1001] = <HTML BLOB>
"""
def get_file_contents_from_GCS(bucket_name: str = BUCKET_NAME, directory: str = GCS_DIRECTORY) -> dict[int, str]:
    client = storage.Client()

    # Client.list_blobs returns an iterator of all my blobs in my bucket
    # A blob is just a reference to a file in GCS, not a file itself
    blob_iterator = client.list_blobs(bucket_name)

    # Consume my iterator into a list 
    blobs = list(blob_iterator)

    # Download the contents of every blob into local memory
    html_pages = {}
    for blob in blobs:
        # stem is the filename minus the filetype
        stem = Path(blob.name).stem
        html_pages[int(stem)] = blob.download_as_text()

    return html_pages

"""
Grab the contents of all the html files in my subdirectory and return that as a string
I am using this function for tests
Outputs the dictionary with example html_pages[1001] = <HTML BLOB>
"""
def get_file_contents_from_disk(directory: str = LOCAL_DIR) -> dict[int, str]:
    # Grab my current directory, jump up, then go into the directory of my html files
    graph_files_dir = Path(__file__).parent / directory


    html_pages = {}
    for path in graph_files_dir.glob("*.html"):
        html_pages[int(path.stem)] = path.read_text(encoding="utf-8")


    return html_pages



"""Return every href value in the page as a list of strings"""
def parse_links(html: str) -> list[int]:
    # This regex was generated by AI. I don't want to make this myself
    LINK_RE = re.compile(r'href\s*=\s*["\'](\d+)\.html["\']', re.IGNORECASE)
    return [int(n) for n in LINK_RE.findall(html)]


"""Average, Median, Max, Min and Quintiles of incoming and outgoing links across all the files."""
def compute_link_properties(pages: list[str]):
    print("TODO")



if __name__ == "__main__":
    # output = get_file_contents_from_GCS()
    output = get_file_contents_from_disk()
    print(output[1001])




